import { createOpenAPI } from "fumadocs-openapi/server";

// The spec is generated by the Go API via `make gen-openapi` (go/api/openapi.json),
// which copies it here. Do not edit by hand.
export const openapi = createOpenAPI({
  input: ["./openapi/openapi.json"],
});
