-- The default read state is now "read": the absence of an entry_read_status
-- row means the article is read. The table stores explicit deviations from
-- the default ('unread', 'removed') and also explicit 'read' rows when the
-- user has marked an article as read (a stronger signal than absence).
-- No data migration is needed — existing 'read' rows are still valid and
-- meaningful, and existing 'unread' rows are still correct.
